version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
#  postgresServerDb:
#    container_name: container-postgres
#    image: postgres:latest
#    ports:
#      - "5022:5432"
#    environment:
#      - POSTGRES_USER=olenukapi
#      - POSTGRES_PASSWORD=*dmUntdOidd3d_#WTi4B9ZoZp%rSDj4Imds07djc*
#      - POSTGRES_DB=olenukDb
#    networks:
#      - myAppNetwork
#    volumes:
#       - d:/web/olenuk/postgresql:/var/lib/postgresql/data  # Use the volume name msvol here
#        - /data/postgresql/data:/var/lib/postgresql/data
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 5

  app:
    container_name: olenuk_container
    image: sergijolenuk50/java-olenuk-api
    ports:
      - "4082:8084"
    networks:
     - myAppNetwork
    depends_on:
      - postgresServerDb
    volumes:
#     - d:/volumes/olenuk-java/images:/app/images  # Use the volume name appvol here
     - /volumes/olenuk-java/images:/app/images  # Use the volume name appvol here
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
  
  client:
    container_name: olenuk_client_container
    image: sergijolenuk50/olenuk_client
    restart: on-failure
    ports:
      - "4081:80"
      

